### PR TITLE
Add support for 2.10.5.3929

### PR DESCRIPTION
**Pull request by FrzMtrsprt**

### CODE REVIEW

**Comment by FrzMtrsprt** [comment]
Yes I have tested it and both offsets work well. I added this version because it's the current packaged version on MS Store. Plenty of users prefer this version, including myself, because it doesn't have auto-update.

**Comment by FrzMtrsprt** [comment]
Also I know there are people who stick to 2.10.3 or even 2.9.x because [UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server) don't work well (at least that's what they think) with 2.10.3+.

**Comment by aliencaocao** [comment]
> Also I know there are people who stick to 2.10.3 or even 2.9.x because [UnblockNeteaseMusic](https://github.com/UnblockNeteaseMusic/server) don't work well (at least that's what they think) with 2.10.3+.

Oh yea I actually tried to use this on my own server but after I set the proxy setting in the client it wouldnt connect so i guess newer version was the reason why it didnt work for me

**Comment by FrzMtrsprt** [comment]
> Oh yea I actually tried to use this on my own server but after I set the proxy setting in the client it wouldnt connect so i guess newer version was the reason why it didnt work for me
Actually it does work on new versions. New versions have stricter SSL verification so you need to install the UnblockNeteaseMusic CA certificate.

**Comment by aliencaocao** [comment]
> Actually it does work on new versions. New versions have stricter SSL verification so you need to install the UnblockNeteaseMusic CA certificate.

Ah so thats why. I'll give it a try. Thanks

**Pull request merged**
