### PR TITLE
Better behaviour when music is paused

### LINKED ISSUE #11: Show music status in presence
### Current behaviour
Music status is not displayed, and music progress is constantly updated even when music is paused
### Improved behaviour
Music status (Playing or Paused) is displayed in a small icon at the corner of the album art, and music progress is hidden when music is paused
### Example
image
image

Note that the small icon should be replaced with a play / pause icon, but I haven't found them yet.

### PR DESCRIPTION
**Pull request by FrzMtrsprt**
Closes #11.

### CODE REVIEW

**Comment by FrzMtrsprt** [comment]
Small play/pause icon is not added yet.

**Comment by aliencaocao** [comment]
thanks, lmk when you are done with the PR

**Comment by FrzMtrsprt** [comment]
We'll need to upload the icons in your Discord Developer Portal, so that we can use them in our rich presence.
I've prepare the two icons and please upload them as `play` and `pause` like this: 
image
Here are the two icon files:
play
pause

**Comment by aliencaocao** [comment]
Ok, i will do it over the weekend. Thanks!

**Comment by aliencaocao** [comment]
@lekoOwO hi could i get your help here in providing the images and names you used in your discord application? I noticed you switched the ID to yours in one of your previous PR. Thanks!

**Comment by FrzMtrsprt** [comment]
Maybe you'll want to change the app id back to your own id, to make life easier in future development and maintenance.

**Comment by aliencaocao** [comment]
> Maybe you'll want to change the app id back to your own id, to make life easier in future development and maintenance.

Yes i am going to, thats why i asked him for what his image resources are so I can port over

**Comment by aliencaocao** [comment]
Oh is it, i thought there are references of images in the code. I will take a closer look on the coming weekend.

**Comment by lekoOwO** [comment]
> @lekoOwO hi could i get your help here in providing the images and names you used in your discord application? I noticed you switched the ID to yours in one of your previous PR. Thanks!

hmmm i really cant find the original resources :(
you get any way to fetch it from dc?

**Comment by aliencaocao** [comment]
> 

Its ok, judging from the code you didn't use any resources.

**Comment by aliencaocao** [comment]
@FrzMtrsprt wait, I don't see anything that uses the 2 small icons. Did you plan to add that in this PR?

**Comment by FrzMtrsprt** [comment]
> @FrzMtrsprt wait, I don't see anything that uses the 2 small icons. Did you plan to add that in this PR?

Yes I was about to add them after you upload the icons lol. It's ok, I'll open other pr.

**Pull request merged**
