### PR TITLE
Supporting more info like cover images, albums, etc.

### PR DESCRIPTION
**Pull request by lekoOwO**
This PR adds the ability to present more music info by getting current playing song id and fetch the info from Netease Cloud Music's webpage.

Thanks to @twinklestar03 for the reverse engineering technique support!

### CODE REVIEW

**Comment by aliencaocao** [comment]
https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/pull/1
Can you checkout this pr and see if the way it fetch the song info locally from temp folders also works?

**Comment by lekoOwO** [comment]
It might work but I dont like the way -- it's unreliable and depends on filesystem
Also, the PR has serious quality issue -- The display texts are not cleared (e.g. modified by {name}), camelCase variable names, uncleared variable/function naming, useless RPC buttons, etc.

**Comment by lekoOwO** [comment]
But it can be preferred if we fetch the information locally first and fetch it on net as the fallback

**Comment by aliencaocao** [comment]
Agree with your points. That PR is actually from someone else's fork and i have yet to get an answer from him on whether i am allowed to merge his fork. Since you opened a PR here, i would merge yours. Please give me a week as i am currently on holiday so can't really test out stuff.

**Comment by lekoOwO** [comment]
Please take your time, I'm not hurrying at it owo
I'm also on holiday too, happy spring festival!

**Comment by aliencaocao** [comment]
Hi @lekoOwO I need some help with github actions...quite new to this stuff
So I have been trying to make pyinstaller add version info into the exe so that users who downloaded the exe will know which version it is (since now the console is hidden). However, I have trouble making my workflow file work.
I use a python package to create a version.txt that will be used by pyinstaller to add the version info. I succeeded in doing this locally, but on github action's VM, the version.txt created seem to be in the wrong location. The creation command ran without error, but pyinstaller complains that the version.txt does not exist. Could you help me see where I did wrong? Thank you

Here is a failed workflow: https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/actions/runs/4031295032/jobs/6930505164

**Pull request merged**
